# Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.

In [1]:
import numpy as np

# Create a numpy array with numbers from 1 to 10
arr = np.arange(1, 11)

# Reshape the array to a 2x5 matrix
reshaped_arr = arr.reshape(2, 5)

print(reshaped_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.

In [6]:
import numpy as np

# Create a numpy array with numbers from 1 to 20
arr = np.arange(1, 21)

# Extract elements between the 5th and 15th index (6th to 15th element)
extracted_elements = arr[5:15]

print(extracted_elements)

[ 6  7  8  9 10 11 12 13 14 15]


# Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4

In [4]:
import pandas as pd

# Create a Pandas Series
data = {'apples': 3, 'bananas': 2, 'oranges': 1}
series = pd.Series(data)

# Add a new item to the Series
series['pears'] = 4

print(series)

apples     3
bananas    2
oranges    1
pears      4
dtype: int64


# Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.

In [9]:
import pandas as pd

# Create a DataFrame
data = {
    'Name': ['Arun', 'Kiran', 'Malu'],
    'Age': [30, 25, 35]
}
df = pd.DataFrame(data)

# Add a new column 'occupation'
df['occupation'] = ['Programmer', 'Manager', 'Analyst']

print(df)

    Name  Age  occupation
0   Arun   30  Programmer
1  Kiran   25     Manager
2   Malu   35     Analyst


# Select the rows of the dataframe where the age is greater than or equal to 30

In [10]:
# Create a DataFrame
data = {
    'Name': ['Arun', 'Kiran', 'Malu'],
    'Age': [30, 25, 35],
    'occupation': ['Programmer', 'Manager', 'Analyst']
}
df = pd.DataFrame(data)

# Select rows where Age is greater than or equal to 30
selected_rows = df[df['Age'] >= 30]

print(selected_rows)

   Name  Age  occupation
0  Arun   30  Programmer
2  Malu   35     Analyst


# Convert this dataframe to a csv file and read that csv file, finally display the contents.

In [11]:
import pandas as pd

# Create a DataFrame
data = {
    'Name': ['Arun', 'Kiran', 'Malu'],
    'Age': [30, 25, 35],
    'occupation': ['Programmer', 'Manager', 'Analyst']
}
df = pd.DataFrame(data)

# Convert the DataFrame to a CSV file
df.to_csv('data.csv', index=False)

# Read the CSV file back into a DataFrame
df_from_csv = pd.read_csv('data.csv')

# Display the contents of the DataFrame
print(df_from_csv)

    Name  Age  occupation
0   Arun   30  Programmer
1  Kiran   25     Manager
2   Malu   35     Analyst
